export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const POST_LOGIN = 'POST_LOGIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';

export const GET_ROOM_BUILDING = 'GET_ROOM_BUILDING';
export const GET_ROOM_BUILDING_SUCCESS = 'GET_ROOM_BUILDING_SUCCESS';
export const GET_ROOM_BUILDING_ERROR = 'GET_ROOM_BUILDING_ERROR';

export const POST_COURSE = 'POST_COURSE';
export const POST_COURSE_SUCCESS = 'POST_COURSE_SUCCESS';
export const POST_COURSE_ERROR = 'POST_COURSE_ERROR';

export const GET_BH = 'GET_BH';
export const GET_BH_SUCCESS = 'GET_BH_SUCCESS';
export const GET_BH_ERROR = 'GET_BH_ERROR';
