const courseStr = {
  intro: 'Giới thiệu',
  giangVien: 'Giảng viên:',
  currentDatestr: '  + currentDate',
  canBoQuanLy: 'Cán bộ quản lý:',
  thoiGian: 'Thời gian:',
  tenKhoa: 'Tên khóa',
  ngay: 'Ngày',
  tuNgay: 'Từ ngày',
  denNgay: 'Đến ngày',
  nhaptenkhoahoc: 'Nhập tên khóa học',
  nhaptengiangvien: 'Nhập tên giảng viên',
  toaNha: 'Tòa nhà:',
  phong: 'Phòng:',
  qliKhoHoc: 'QUẢN LÝ KHÓA HỌC',
  qliBuoiHoc: 'QUẢN LÝ BUỔI HỌC',
  newKhoaHoc: 'TẠO MỚI KHÓA HỌC',
  content: 'Nội dung',
  course: 'Khóa học',
  lesson: 'Bài giảng',
  test: 'Bài thi',
  process: 'Tiến trình',
  myCoure: 'Khóa học của tôi',
  recomentCoure: 'Khóa học khuyến nghị',
  search: 'Tìm kiếm',
  free: 'Tự do',
  censorship: 'Kiểm duyệt',
  discuss: 'Trao đổi',
  note: 'ghi chú',
  reply: 'Trả lời',
  remove: 'Xóa',
  save: 'LƯU',
  edit: 'Sửa',
  register: 'Đăng ký',
  join: 'Vào học',
  watting: 'Chờ duyệt...',
  more: 'Xem thêm...',
  hide: 'Ẩn đi...',
  notFound: 'Không tìm thấy khóa học nào cả!',
  error: 'Lỗi',
  close: 'Đóng',
  failCallAPI: 'Không kết nối được tới máy chủ',
  notNetwork: 'Không có kết nối mạng',
};

export default courseStr;
